### ISSUE TITLE
更新后，服务器信息栏框体的锚点似乎变为中间了

### ISSUE THREAD

**Issue by Annullare** [ottercorp/Dalamud#44]
更新后，服务器信息栏的字数或者总长度发生变化时，框体会以中心为锚点发生长度改变，但开启并关闭界面设置后位置恢复“正常”
后面发现框体会以最后一次关闭界面设置后的状态将锚点置于当前框体的中心
正常
![1](https://github.com/ottercorp/Dalamud/assets/42252672/248e8a39-0f5e-4f01-939b-7d8c8ddd1148)
关闭界面设置后，随便加点什么，再打开
![2](https://github.com/ottercorp/Dalamud/assets/42252672/8d020666-a26c-4bc8-aa99-1ebf938ace8b)
关闭界面设置后再打开一次
![3](https://github.com/ottercorp/Dalamud/assets/42252672/3306992b-baed-427e-88af-57531e69033e)
这次是删点东西后
![4](https://github.com/ottercorp/Dalamud/assets/42252672/557baaf9-0e93-4866-acac-fbfe44436ddb)

**Comment by Annullare** [comment]
![reply](https://github.com/ottercorp/Dalamud/assets/42252672/d3efee09-928b-46ff-b015-30b653afa717)
This issue was fixed in Dalamud a couple of weeks ago. Based on the language in the screenshots it appears you may be using a Dalamud fork? If so, the fork needs to update to get this fix.

**Comment by Bluefissure** [comment]
似乎相关代码经过多个 commit 修正、也包含 CS 更新，cherry-pick 容易导致问题，请等待 6.5 版本 API9 后的更新一同修复。
相关 PR: https://github.com/goatcorp/Dalamud/pull/1494
