### ISSUE TITLE
CN Patch 6.5

### ISSUE THREAD

**Issue by Bluefissure** [ottercorp/Dalamud#46]
CN Patch 6.5 is going to be [released on Mar 05](https://ff.web.sdo.com/web8/index.html#/newstab/newscont/358605) things that need to be updated:

- [x] [XIVLauncherCN](https://github.com/ottercorp/FFXIVQuickLauncher) (@wozaiha, @Loskh)
- [x] [XIVLauncher.Core](https://github.com/ottercorp/XIVLauncher.Core) (@Bluefissure)
- [x] [Plogon](https://github.com/ottercorp/Plogon) API9 (@Bluefissure)
- [x] [XLWebServices-fastapi](https://github.com/ottercorp/XLWebServices-fastapi) API9 (@Bluefissure, @subjadeites)
- [x] [Dalamud](https://github.com/ottercorp/Dalamud) API9 (@Bluefissure, @Loskh) **sig和字体需要二次检查**
- [x] [Main repo plugins](https://github.com/ottercorp/DalamudPluginsD17) (@MapleRecall, @wozaiha, @Loskh, @Bluefissure) 可能需要特供：[列表](https://github.com/ottercorp/DalamudPluginsD17/issues/181)
- [x] [FFCS](https://github.com/ottercorp/FFXIVClientStructs/tree/6.5) branch 6.5 done

<details>
  <summary>Hidden Section</summary>

- [x] [Penumbra](https://github.com/MeowZWR/Penumbra-CN), [Glamourer](https://github.com/MeowZWR/Glamourer-CN) (@MeowZWR)
- [x] Mare([Server](https://github.com/Bluefissure/Mare-server/tree/CN), [Client](https://github.com/Bluefissure/Mare-client/tree/CN)) (@Bluefissure, @MeowZWR)

</details>

**Comment by Bluefissure** [comment]
API9 Changes: [What's New in Dalamud v9](https://dalamud.dev/versions/v9)

**Comment by wozaiha** [comment]
[FFCS](https://github.com/ottercorp/FFXIVClientStructs/tree/6.5) for 6.5

**Comment by wozaiha** [comment]
IME输入中文有候选框时卡顿
如果不选择候选文字而是点击候选框外位置会关闭候选框并锁死鼠标位置
Alt+Tab可救

**Comment by Loskh** [comment]
IME在候选词很长的时候会卡，国际服也是这样，和输入法无关，以后再修
