### ISSUE TITLE
AppData路径存在中文时无法创建或保存dalamudUI.ini

### ISSUE THREAD

**Issue by wozaiha** [ottercorp/Dalamud#50]
AppData路径存在中文时无法创建或保存dalamudUI.ini

ImGuiNet 中的 IniFilename 似乎被定义为ASCII编码？
可能还有其他问题？

**Comment by Loskh** [comment]
单独运行lib/ImGuiSceneTest可以在中文路径创建或保存dalamudUI.ini，可能是Dalamud的问题
